# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    paths:
      - 'FLN-Backend/**'
      - '.github/workflows/gradle.yml'
    branches: [ "main" ]
  pull_request:
    paths:
      - 'FLN-Backend/**'
      - '.github/workflows/gradle.yml'
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        repository: CS5520-MobileAppsSeattle/final-project-fln/FLN-Backend
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      working-directory: ./FLN-Backend
      run: gradle clean build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with: 
        path: /backend/spring/
