// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl6SCgXg_HWonXcs32a2NJzTwPrSXaHlA',
    appId: '1:941757793553:android:7bbc08261ff3c9674c78b0',
    messagingSenderId: '941757793553',
    projectId: 'friend-lover-or-nothing',
    storageBucket: 'friend-lover-or-nothing.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlw1xPtJPy8w27E57GlJR9z-cp7VZW7HM',
    appId: '1:941757793553:ios:c1d8909e0f38f0624c78b0',
    messagingSenderId: '941757793553',
    projectId: 'friend-lover-or-nothing',
    storageBucket: 'friend-lover-or-nothing.appspot.com',
    androidClientId: '941757793553-tpo5jsmeso2bhdgf9dvpbjvnf46l3eoj.apps.googleusercontent.com',
    iosClientId: '941757793553-5i7kvqlu1n6361metr6df5uftnqrbv72.apps.googleusercontent.com',
    iosBundleId: 'com.nu.cs5520.fln.friendLoverNothing',
  );
}
